'use strict';
/* ================= LORE ==================================================
   Narrative text, separated from mechanics. Each key below is an EVENTS
   entry id (js/data.js) mapped to its array of prose variants — the same
   content that used to live inline as `v:[...]` on the event object.

   Pattern: mechanics tables (EVENTS, DECISIONS, ...) stay in data.js and
   hold triggers/effects (`a`, `cd`, `if`, `fx`, `side`, `follow`); prose
   variants live here, looked up by id via loreV(id). This keeps tone/copy
   edits separate from balance/logic edits.

   Only EVENTS has been migrated so far, as the reference implementation —
   it's the purest narrative table. Other tables (DECISIONS, PURSUITS,
   CRISES, OPPORTUNITIES, etc.) still hold their prose inline; migrate them
   the same way, table by table, when it's worth the diff.
   ========================================================================= */
function loreV(id){ return LORE[id]||[]; }
const LORE={
 ancestorname:['Subject was named, in part, for {ancestor}, who came before. {ancestorFate}.'],
 ancestortale:['Subject was told, early and often, about {ancestor}. {ancestorFate}. The stories varied by teller; the ending never did.','Subject grew up under a portrait of {ancestor}, who watched from the wall and said nothing. {ancestorFate}.'],
 firstword:['Subject said a first word. It was “no.” The Bureau considers this prophetic.','Subject said a first word. It was, unfortunately, “more.”'],
 steps:['Subject took first steps. Fell. Rose again. The Bureau notes resilience.'],
 measles:['Subject contracted the measles. Recovered after a feverish week.','Subject contracted the measles and gave it to the entire household, democratically.'],
 argument:['Subject was observed hiding under the table during a family argument.','Subject counted the cracks in the ceiling during a family argument. There were many.'],
 crayon:['Subject drew on the wall. The drawing was, admittedly, good.','Subject drew on the wall. The drawing was, admittedly, the subject’s best work.'],
 coin:['A grandparent slipped the subject a coin, against regulations.','A grandparent slipped the subject a coin and unsolicited advice, both against regulations.'],
 spelling:['Subject won the spelling competition, spelling “bureaucracy” correctly first try.','Subject won the spelling competition. The prize was a book about bees. Subject remains bitter.'],
 marbles:['Subject traded lunch rations for marbles. Net profit: {n} marbles.','Subject traded lunch rations for a penknife. The teacher confiscated the knife and the business model.'],
 tree:['Subject fell from a tree. The tree was fine.','Subject fell from a tree onto a smaller child. Both filed complaints.'],
 friend:['Subject made a close friend, {friend}. The two were inseparable, briefly.','Subject made a close friend, {friend}. They swore a blood oath. The teacher administered iodine.'],
 cane:['Subject was caned for talking in class. Subject had been talking about the lesson.','Subject was caned for talking in class. The lesson, notably, had not been about caning.'],
 capable:['A teacher wrote: “capable, if applied.” The subject did not apply.','A teacher wrote: “a mystery, and not in the flattering sense.”'],
 beetles:['Subject collected beetles in a jar, then released them. Growth noted.','Subject collected beetles in a jar. The jar collected judgment from the neighbors.'],
 growth:['Subject grew four inches in a summer. Coordination did not keep pace.','Subject grew four inches in a summer. The doorframes did not keep pace either.'],
 heartbreak1:['Subject experienced a first heartbreak. The Bureau files it under “character-building.”','Subject experienced a first heartbreak and announced it to the street. The street sympathized, loudly.'],
 exams:['Subject passed examinations with marks the school called “adequate.”','Subject passed examinations. The family celebrated as if “adequate” were a country they had won.'],
 examsfail:['Subject failed two examinations. Blamed the lighting.','Subject failed two examinations and one teacher’s patience.'],
 smoking:['Subject was seen behind the gymnasium, smoking. The cigarette was confiscated. The habit was not.','Subject smoked behind the gymnasium, claiming it was “for the lungs.” The lungs disagreed.'],
 acne:['Acne. Significant.','Acne. The Bureau declines to elaborate.'],
 heartbreak2:['Subject’s heart was broken again. Subject wrote {n} pages about it.','Subject’s heart was broken again. Subject wrote {n} pages and mailed none of them.'],
 motorcycle:['Subject bought a motorcycle, against all available advice.','Subject bought a motorcycle. The advice against it was unanimous, which the subject found persuasive the wrong way.'],
 rentroom:['Subject moved into a rented room with a leaky ceiling and a philosophical landlord.','Subject moved into a rented room. The previous tenant left a chair and a warning about the stairs.'],
 books:['Subject read three books in a month. Something shifted.','Subject read three books in a month and began correcting the newspaper. Something shifted.'],
 cough:['Subject developed a persistent cough. The cough developed a schedule.','Subject’s cough arrived each winter like a relative with nowhere else to go.'],
 back:['Subject’s back went out lifting a box of nothing at all.','Subject’s back went out tying a shoe. The shoe was not even difficult.'],
 audit:['Subject was audited by the Bureau. Everything was in order. Barely.','Subject was audited. The auditor found nothing, which disappointed them both.'],
 uncle:['Subject inherited a small sum from an uncle nobody remembered.','Subject inherited a small sum from an uncle nobody remembered, and a clock that ran backwards.'],
 hair:['Subject’s hair thinned. Subject pretended not to notice. Everyone pretended.','Subject’s hair thinned. Subject bought a hat. The hat did not pretend.'],
 moderately:['Subject’s doctor used the word “moderately” several times, meaningly.','Subject’s doctor used the word “moderately” several times, then billed for it.'],
 letters:['Subject re-read old letters. Some were to people who no longer answered.','Subject re-read old letters and found, with alarm, they were now letters from an old person.'],
 pigeons:['Subject fed the pigeons daily. They knew the subject by sight and by bread.','Subject fed the pigeons daily. The fat one was clearly in charge.'],
 knees:['Subject’s knees announced the weather with perfect accuracy.','Subject’s knees announced the weather. The meteorological service did not return the favor.'],
 friendgone:['An old friend, {friend}, passed away. Subject attended the funeral in good weather.','An old friend, {friend}, passed away. Subject stayed after the funeral, helping with the chairs.'],
 hip:['Subject fell and broke a hip. The hip was repaired. The confidence was not.','Subject fell and broke a hip. The hospital food was discussed at length, and not fondly.'],
 grandvisit:['Subject’s grandchildren visited. The house was loud. Subject complained, then smiled.','Subject’s grandchildren visited and rearranged nothing, which the subject called a miracle.'],
 stories:['Subject told long stories. They were, the Bureau concedes, good stories.','Subject told long stories. The Bureau concedes they improved with each telling. Factually, no.'],
 flu:['Subject contracted influenza. Stayed home. Read. Recovered, mostly.','Subject contracted influenza and was nursed by whoever lost the coin toss.'],
 pickpocket:['Subject was pickpocketed at the market. The thief was never found, but was clearly skilled.','Subject was pickpocketed. What was taken: money. What was gained: a story, eventually.'],
 lottery:['Subject won a small sum in the lottery and told everyone.','Subject won a small sum in the lottery. The sum was small. The telling was not.'],
 drinkalone:['Subject began drinking alone. The Bureau files this separately from drinking with colleagues.','Subject began drinking alone. The bottle kept more reliable hours than the subject’s friends.'],
 gamble:['Subject discovered the racetrack. The racetrack discovered the subject’s savings.','Subject backed a horse named Honest Bureaucrat. The horse, like the institution, disappointed.'],
 paidcompany:['Subject spent an evening at a house of negotiable company. The Bureau adjusted the asset column and filed the rest under “private.”','Subject spent an evening where affection was priced by the hour. The negotiation was brief. The regret was not.'],
 theft:['Subject was caught taking what was not theirs. The magistrate, mercifully, called it “youthful.”','Subject was arrested for petty theft. The matter ended with a fine and a look that lasted longer.'],
 contraband:['Subject began moving small parcels of contraband for coin. The money was good.','Subject began moving small parcels of contraband. The knock at the door, when it came, was louder than the money.'],
 affair:['Subject’s attention wandered from the marriage. The file notes the wandering was not discreet.','Subject’s attention wandered from the marriage. The wandering left letters, which is how these things end.'],
 shark:['Subject borrowed from a man who did not send invoices. He sent other things.','Subject borrowed from a man with an abacus and two friends. The interest was “reasonable” by no one.'],
 scuffle:['A scuffle behind the dance hall, over a misunderstanding about a hat, left bruises.','A scuffle behind the dance hall. The hat was, in the end, not worth it.'],
 backroom:['Subject’s new acquaintances were thin, polite, and always borrowing money. The back room took its toll.','Subject began keeping late hours in a room where the lamps never went out. Health and money went out instead.'],
 disturbance:['There were disturbances at the subject’s address, late and loud. The neighbors filed nothing. The subject filed nothing either.','There were late disturbances at the address, of the kind the file records in a smaller hand.'],
 bridge:['Subject stood a long while at the river rail, watching the water. A passerby talked about the weather until the subject walked home. The Bureau notes, in a careful hand: walked home — and the next day, called an old friend.','Subject sat a long time where the water does its paperwork. A stranger complained about the rain, at length, to nobody. Subject went home. The Bureau notes, carefully: went home — and wrote a letter they had been putting off.'],
 academiccite:['Subject was cited by a rival department, grudgingly.','A student quoted the subject’s own lecture back at them, word for word. Flattering, mostly.'],
 academiagrant:['A small research grant came through, with a great deal of paperwork attached.','Subject’s proposal was funded, on the third submission, by a committee that had lost the first two.'],
 medsave:['Subject caught something the chart had missed. The patient sent flowers, unnecessarily.','A late diagnosis, made just in time. Subject went home and slept for eleven hours.'],
 medshift:['A double shift, unplanned, unpaid extra, and entirely necessary.','The ward was short-staffed again. Subject stayed. Someone always stays.'],
 lawwin:['Subject won a case the office had already written off. It made the newsletter.','Subject won a case on a technicality the senior partners pretended to have thought of first.'],
 lawlose:['Subject lost a case that should have been unlosable. The client took it worse than the subject did.','A ruling went the wrong way, for reasons the subject is still drafting a memo about.'],
 engfix:['Subject found the fault the whole team had missed. It was, of course, a loose wire.','A structural problem was solved on a napkin at lunch. The napkin was later filed as an official document.'],
 engoverrun:['The project ran over budget and over schedule, in that order.','A deadline was missed by a margin the subject called “rounding.”'],
 archwin:['A design was praised in a trade paper nobody the subject knows reads, which somehow made it better.','Subject’s plan was chosen over three others, for reasons the committee declined to specify.'],
 archredesign:['The client changed their mind. Then changed it back. Then changed it again.','A whole wing was redrawn overnight because someone measured the plot wrong, and it was not the subject.'],
 bizdeal:['A deal closed better than projected. Someone bought the subject a drink to say so.','The numbers came back favorable, twice, which made everyone suspicious and then pleased.'],
 bizaudit:['An internal audit found nothing, after finding the subject’s patience first.','The books balanced, eventually, after a long evening and several pots of coffee.'],
 labaccident:['A near-miss on the shop floor. Subject walked away with a bruise and a story.','A machine jammed at the worst possible moment. Subject still has all their fingers, which colleagues remarked on.'],
 tradeorder:['A big order came in, and the shop delivered it a day early, out of sheer stubbornness.','Subject fixed something the manufacturer said couldn’t be fixed. It could.'],
 transdelay:['A delivery was delayed by weather, a washed-out road, and one uncooperative mule.','The schedule fell apart by midmorning. Subject rebuilt it by lunch, badly, but it held.'],
 transrecord:['Subject beat the route’s old time record, unofficially, and told everyone officially.','A full day’s deliveries, without a single miss. The log was almost suspiciously clean.'],
 culinaryreview:['A local paper reviewed the kitchen favorably, using the word “surprising” more than once.','A regular customer requested the subject by name. The subject pretended not to be pleased.'],
 culinarydisaster:['A sauce broke, a delivery didn’t arrive, and the evening service happened anyway, somehow.','Subject burned a dish beyond rescue and served the backup with a straight face.'],
 agriharvest:['A good harvest, better than the almanac predicted and the soil deserved.','The yield came in high this year. Subject allowed themselves one evening of feeling good about it.'],
 agriblight:['A blight took part of the crop before anyone noticed the spots.','A hard frost came early and took more than the almanac warned it might.'],
 carethanks:['A patient’s family sent a card, handwritten, which the subject kept longer than intended.','Someone the subject looked after, years back, came back just to say thank you.'],
 careexhaust:['A hard week, back to back, with no good place to put the feeling of it.','Subject covered a shift, then another, and started to lose track of which day it was.'],
 retailrush:['A holiday rush went better than staffing should have allowed.','The shop had its best week in a year, and the subject’s feet noticed first.'],
 retailtheft:['Someone walked out with stock and a straight face. It happens.','A till came up short at closing. Nobody was accused. Everybody was suspected.'],
 fashioncommission:['A commission came in for something the subject had never quite made before. It worked.','A client asked for the impossible and, on the third fitting, got something close enough.'],
 fashioncopy:['A rival shop copied the design, badly, and everyone who mattered noticed.','Someone else took the credit for the subject’s pattern. The subject kept the receipts.'],
 artsrave:['A performance landed better than expected. The applause ran long enough to be awkward.','A critic used the word “promising,” which the subject has decided to take as a compliment.'],
 artsflop:['A performance fell flat. The silence afterward said more than any review would.','The house was thin and the room colder than the material deserved.'],
 athleticswin:['A close finish, subject’s favor, by a margin nobody could quite agree on.','Subject took the match on effort alone, and paid for it the next morning.'],
 athleticsinjury:['A pulled muscle, mid-competition, walked off rather than carried off, barely.','A hard fall cost the subject the match and most of the following week.'],
 diplowin:['A negotiation held, against most expectations in the room.','Subject found the one sentence both sides could agree to sign.'],
 diplotense:['A meeting went long, then cold, then nowhere, then home.','Subject spent the evening drafting an apology neither side had technically requested.'],
 underworldscore:['A job went clean, quiet, and profitable, which is rarer than any of the three alone.','The take was better than promised, which made everyone involved briefly, uncharacteristically cheerful.'],
 underworldheat:['Someone was asking questions with a badge attached. The job was postponed, not forgotten.','A tip went around that the wrong people were watching. Subject kept a low profile for a while.'],
};
