'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {createGameContext}=require('./helpers/vm-loader');
function ctx(){return createGameContext(['js/systems/condition-registry.js','js/systems/medical-system.js']);}
test('medical core source has no UTF-8 byte-order mark',()=>{const bytes=fs.readFileSync('js/systems/medical-system.js');assert.notEqual(bytes[0],0xEF);assert.equal(bytes.toString('utf8').charCodeAt(0),"'".charCodeAt(0));});
test('registry is immutable and complete',()=>{const c=ctx();assert.equal(c.ConditionRegistry.allConditions().length,5);assert.equal(c.ConditionRegistry.allTreatments().length,4);const x=c.ConditionRegistry.condition('injury');x.name='x';assert.equal(c.ConditionRegistry.condition('injury').name,'Lingering injury');assert.equal(c.ConditionRegistry.condition('none'),null);});
test('migration is deterministic for subject and NPC shapes',()=>{const c=ctx(),a={id:'A',age:40,health:60,conditions:[{id:'strain',severity:2,known:true,years:2}]};c.MedicalSystem.ensureMedicalState(a,{year:1960});const json=JSON.stringify(a);c.MedicalSystem.migrate(a,{year:1960});assert.equal(JSON.stringify(a),json);assert.equal(a.medical.conditions[0].state,'diagnosed');assert.equal(c.MedicalSystem.checkInvariants(a).length,0);const n={id:'npc:test',birthYear:1920,health:{general:72,conditions:[]}};c.MedicalSystem.ensureMedicalState(n,{year:1960});assert.equal(n.health.general,72);assert.strictEqual(n.health.conditions,n.health.medical.conditions);});
test('active episode merges and resolved episode receives a new identity',()=>{const c=ctx(),p={id:'person',age:30,health:80,healthCap:100,conditions:[]},w={seed:'x',year:1950};const first=c.MedicalSystem.addCondition(p,'injury',3,{world:w});assert.strictEqual(c.MedicalSystem.addCondition(p,'injury',5,{world:w}),first);assert.equal(first.severity,5);first.state='resolved';const second=c.MedicalSystem.addCondition(p,'injury',2,{world:w});assert.notEqual(second.instanceId,first.instanceId);assert.equal(p.medical.conditions.length,2);});
test('core has no global random or active-game references',()=>{const src=fs.readFileSync('js/systems/medical-system.js','utf8');assert.doesNotMatch(src,/Math\.random\(|Random\.next\(|(?<![.\w])chance\(|(?<![.\w])pick\(|(?<![.\w])RI\(|(?<![.\w])R\(/);assert.doesNotMatch(src,/(?<![.\w])S(?![\w])|(?<![.\w])World(?![\w])/);});
test('new subject state has schema two aliases and counters',()=>{const c=ctx(),p={id:'subject:one',age:20,health:70,conditions:[]};const m=c.MedicalSystem.ensureMedicalState(p,{year:1940});assert.equal(m.schemaVersion,2);assert.strictEqual(p.conditions,m.conditions);assert.equal(m.instanceCounter,0);assert.equal(m.actionCounter,0);assert.equal(c.MedicalSystem.activeConditions(p).length,0);});
test('legacy schema preserves history and creates stable instance ids',()=>{const c=ctx(),p={id:'legacy',age:40,health:60,conditions:[{id:'strain',severity:2,known:true,years:2}],medical:{schemaVersion:1,history:[{kind:'note'}],conditions:[{id:'strain',severity:2,known:true,years:2}]}};c.MedicalSystem.migrate(p,{year:1960});const x=p.medical.conditions[0];assert.equal(x.definitionId,'strain');assert.equal(x.id,'strain');assert.equal(x.state,'diagnosed');assert.equal(x.yearsActive,2);assert.match(x.instanceId,/^condition:legacy:1960:0001$/);assert.equal(p.medical.history.length,1);});
test('unknown legacy definitions remain opaque and are reported by invariants',()=>{const c=ctx(),p={id:'unknown',age:40,health:60,conditions:[{id:'retired-diagnosis',severity:4,state:'remission',years:3,source:'old save'}]};c.MedicalSystem.migrate(p,{year:1960});const x=p.medical.conditions[0];assert.equal(x.definitionId,'retired-diagnosis');assert.equal(x.id,'retired-diagnosis');assert.equal(x.severity,4);assert.equal(x.state,'remission');assert.equal(x.yearsActive,3);assert.equal(x.source,'old save');assert.equal(x.exposureType,'unknown');assert.equal(x.contagious,false);assert.match(JSON.stringify(p),/retired-diagnosis/);assert.deepEqual(Array.from(c.MedicalSystem.checkInvariants(p)),['unknown condition definition: retired-diagnosis']);});
test('duplicate malformed and foreign instance IDs are reconciled in array order',()=>{const c=ctx(),p={id:'Person X',age:30,health:70,conditions:[{id:'injury',instanceId:'condition:person-x:1950:0001'},{id:'strain',instanceId:'condition:person-x:1950:0001'},{id:'infection',instanceId:'bad'},{id:'respiratory',instanceId:'condition:other:1950:0007'}]};c.MedicalSystem.migrate(p,{year:1950});const ids=p.medical.conditions.map(x=>x.instanceId);assert.equal(ids[0],'condition:person-x:1950:0001');assert.equal(new Set(ids).size,4);assert.ok(ids.slice(1).every(id=>/^condition:person-x:1950:\d{4,}$/.test(id)));});
test('encoded and persisted counters determine the next episode identity',()=>{const c=ctx(),p={id:'counter',age:30,health:70,conditions:[{id:'injury',instanceId:'condition:counter:1950:0001'},{id:'strain',instanceId:'condition:counter:1950:0005'}],medical:{instanceCounter:9}};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.instanceCounter,9);p.medical.conditions[0].state='resolved';const next=c.MedicalSystem.addCondition(p,'injury',2,{world:{year:1950}});assert.match(next.instanceId,/:0010$/);});
test('onset year normalizes before id reconciliation and migration is idempotent',()=>{const c=ctx(),p={id:'year',age:20,health:70,conditions:[{id:'injury',onsetYear:1950.6},{id:'strain',onsetYear:NaN}]};c.MedicalSystem.migrate(p,{year:1960});assert.equal(p.medical.conditions[0].onsetYear,1951);assert.equal(p.medical.conditions[1].onsetYear,1960);const snapshot=JSON.stringify(p.medical);c.MedicalSystem.migrate(p,{year:1960});assert.equal(JSON.stringify(p.medical),snapshot);});
test('zero severity is valid while absent and invalid severities use definition defaults',()=>{const c=ctx(),p={id:'zero',age:30,health:70,conditions:[]},w={year:1950};const zero=c.MedicalSystem.addCondition(p,'injury',0,{world:w});assert.equal(zero.severity,0);assert.equal(c.MedicalSystem.addCondition(p,'injury',0,{world:w}).severity,0);zero.state='resolved';assert.equal(c.MedicalSystem.addCondition(p,'strain',undefined,{world:w}).severity,2);p.medical.conditions.find(x=>x.id==='strain').state='resolved';assert.equal(c.MedicalSystem.addCondition(p,'infection',NaN,{world:w}).severity,3);});
test('save reload migration preserves condition identity and counters',()=>{const c=ctx(),p={id:'save',age:30,health:70,conditions:[]};c.MedicalSystem.addCondition(p,'injury',3,{world:{year:1950}});const saved=JSON.parse(JSON.stringify(p));c.MedicalSystem.migrate(saved,{year:1950});assert.deepEqual(JSON.parse(JSON.stringify(saved.medical)),JSON.parse(JSON.stringify(p.medical)));});
test('normalization uses explicit person age rather than global subject',()=>{const c=ctx(),a={id:'a',age:13,health:70,conditions:[]},b={id:'b',age:61,health:70,conditions:[]};c.S={age:99,health:1};const x=c.MedicalSystem.addCondition(a,'strain',2,{world:{year:1930}}),y=c.MedicalSystem.addCondition(b,'chronic',3,{world:{year:1980}});assert.equal(x.onsetAge,13);assert.equal(y.onsetAge,61);});
test('invalid partial medical data is repaired safely',()=>{const c=ctx(),p={id:'repair',age:30,health:NaN,conditions:[{id:'injury',severity:NaN}],medical:{conditions:null,history:null,instanceCounter:-3,actionCounter:'bad'}};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.instanceCounter,1);assert.equal(p.medical.actionCounter,0);assert.ok(Array.isArray(p.medical.history));assert.ok(Array.isArray(p.medical.conditions));assert.equal(c.MedicalSystem.checkInvariants(p).length,0);});
test('history is bounded to the latest twenty four records',()=>{const c=ctx(),p={id:'history',age:20,health:70,conditions:[]};for(let i=0;i<30;i++)c.MedicalSystem.history(p,'note',null,String(i),{world:{year:1900+i}});assert.equal(p.medical.history.length,24);assert.equal(p.medical.history[0].note,'6');});
test('isolated streams are deterministic and do not advance personal random',()=>{const c=ctx(),w={seed:'medical-test',year:1950},p={id:'rng',age:30,health:70,conditions:[]};c.Random.setSeed('personal');const first=c.Random.next(),control=c.Random.next();c.Random.setSeed('personal');assert.equal(c.Random.next(),first);const a=c.MedicalSystem.stream(w,p,1950,'migration','a').next(),b=c.MedicalSystem.stream(w,p,1950,'migration','a').next();assert.equal(a,b);assert.equal(c.Random.next(),control);});
test('public API includes reusable care methods and annual progression methods',()=>{const c=ctx(),keys=Object.keys(c.MedicalSystem);['contextFor','accessFor','exposureRisk','expose','examine','treatmentOptions','treatmentCost','treat','hoursPenalty','educationPenalty','workPenalty','summary','tickPerson','mortalityDetails','rollMortality'].forEach(key=>assert.equal(typeof c.MedicalSystem[key],'function'));['startOutbreak','tickOutbreak'].forEach(key=>assert.equal(keys.includes(key),false));});
test('known lifecycle states imply known while symptomatic known remains valid',()=>{const c=ctx();['diagnosed','treated','remission','chronic'].forEach(state=>{const p={id:state,age:30,health:70,conditions:[{id:'injury',state,known:false}]};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.conditions[0].known,true);});const p={id:'symptomatic',age:30,health:70,conditions:[{id:'injury',state:'symptomatic',known:true}]};c.MedicalSystem.migrate(p,{year:1950});assert.equal(c.MedicalSystem.checkInvariants(p).length,0);});
test('raw subject and npc health is repaired during migration',()=>{const c=ctx(),s={id:'s',age:20,health:NaN,healthCap:80,conditions:[]},n={id:'n',birthYear:1900,health:{general:NaN,conditions:[]}};c.MedicalSystem.migrate(s,{year:1950});c.MedicalSystem.migrate(n,{year:1950});assert.equal(s.health,50);assert.equal(n.health.general,70);s.health=120;c.MedicalSystem.migrate(s,{year:1950});assert.equal(s.health,80);s.health=-2;c.MedicalSystem.migrate(s,{year:1950});assert.equal(s.health,0);});
test('zero instance counter is repaired and migration stays stable',()=>{const c=ctx(),p={id:'zero-id',age:20,health:70,conditions:[{id:'injury',instanceId:'condition:zero-id:1950:0000'}]};c.MedicalSystem.migrate(p,{year:1950});assert.equal(/:0000$/.test(p.medical.conditions[0].instanceId),false);const snapshot=JSON.stringify(p.medical);c.MedicalSystem.migrate(p,{year:1950});assert.equal(JSON.stringify(p.medical),snapshot);});

// --- Phase 4A-3: annual progression and mortality ---
function zeroRng(){return {next:()=>0};}
function oneRng(){return {next:()=>0.999999};}
test('tickPerson is idempotent for the same person-year and does not rewind on a stale year',()=>{const c=ctx(),p={id:'idem',age:30,health:70,conditions:[]},w={seed:'x',year:1950};const first=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(first.applied,true);const second=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(second.applied,false);assert.equal(second.reason,'already-applied');const before=JSON.stringify(p.medical);const stale=c.MedicalSystem.tickPerson(w,p,{world:w,year:1949});assert.equal(stale.applied,false);assert.equal(stale.reason,'stale-year');assert.equal(JSON.stringify(p.medical),before);const next=c.MedicalSystem.tickPerson(w,p,{world:w,year:1951});assert.equal(next.applied,true);assert.equal(p.medical.lastTickYear,1951);});
test('tickPerson does not consume actionCounter or the global personal random stream',()=>{const c=ctx(),p={id:'rng-safe',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.Random.setSeed('personal');const before=c.Random.next();c.Random.setSeed('personal');c.MedicalSystem.addCondition(p,'injury',4,{world:w});const counterBefore=p.medical.actionCounter;c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(p.medical.actionCounter,counterBefore);assert.equal(c.Random.next(),before);});
test('latent condition decrements incubation and becomes symptomatic exactly once with one history entry',()=>{const c=ctx(),p={id:'latent',age:20,health:70,conditions:[{id:'infection',state:'latent',known:false,incubationLeft:1}]},w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const cond=p.medical.conditions[0];assert.equal(cond.state,'symptomatic');assert.equal(p.medical.history.filter(h=>h.kind==='symptom').length,1);c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(p.medical.history.filter(h=>h.kind==='symptom').length,1);});
test('treatment filed in the current year is protected from untreated burden and receives no course relief until next year',()=>{const c=ctx(),p={id:'grace',age:30,health:70,healthCap:100,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'injury',4,{world:w,known:true,state:'diagnosed'});const cond=p.medical.conditions[0];cond.known=true;cond.state='treated';cond.treated=true;cond.treatment='basic';cond.lastTreatmentYear=1950;const result=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(result.healthDelta,0);assert.equal(cond.state,'treated');assert.equal(cond.severity,4);const nextYear=c.MedicalSystem.tickPerson(w,p,{world:w,year:1951});assert.notEqual(nextYear.healthDelta,undefined);assert.notEqual(cond.state,'treated');});
test('untreated burden formula applies health, strain happiness, and hour penalties correctly',()=>{const c=ctx(),p={id:'burden',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'strain',5,{world:w,known:true,state:'diagnosed'});const result=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(result.healthDelta,-3);assert.equal(result.happinessDelta,-3);assert.equal(result.yearHoursPenalty,2);});
test('chronic conversion preserves instanceId when no existing chronic record and merges into one chronic record otherwise',()=>{const c=ctx(),p={id:'chronic',age:30,health:70,conditions:[]},w={seed:'chronic-seed',year:1950};c.MedicalSystem.addCondition(p,'respiratory',3,{world:w,known:true,state:'diagnosed'});p.medical.conditions[0].yearsActive=3;const originalId=p.medical.conditions[0].instanceId;const streamFor=()=>({next:()=>0});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950},{streamFor});const chronicCondition=p.medical.conditions.find(x=>x.definitionId==='chronic');assert.ok(chronicCondition);assert.equal(chronicCondition.instanceId,originalId);c.MedicalSystem.addCondition(p,'infection',3,{world:w,known:true,state:'diagnosed'});p.medical.conditions.find(x=>x.definitionId==='infection').yearsActive=3;c.MedicalSystem.tickPerson(w,p,{world:w,year:1951},{streamFor});const activeChronic=c.MedicalSystem.activeConditions(p).filter(x=>x.definitionId==='chronic');assert.equal(activeChronic.length,1);});
test('mortalityDetails contributes only for severe untreated conditions and clamps risk to 0.16, no randomness or mutation',()=>{const c=ctx(),p={id:'mortal',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'injury',5,{world:w,known:true,state:'diagnosed'});c.MedicalSystem.addCondition(p,'chronic',5,{world:w,known:true,state:'diagnosed'});p.medical.conditions[0].yearsActive=10;p.medical.conditions[1].yearsActive=10;c.MedicalSystem.syncLegacy(p);const before=JSON.stringify(p.medical);const details=c.MedicalSystem.mortalityDetails(w,p,{world:w,year:1950});assert.ok(details.risk>0);assert.ok(details.risk<=0.16);assert.equal(JSON.stringify(p.medical),before);const treated={id:'t',age:30,health:70,conditions:[]};c.MedicalSystem.addCondition(treated,'injury',5,{world:w,known:true,state:'treated'});const noContribution=c.MedicalSystem.mortalityDetails(w,treated,{world:w,year:1950});assert.equal(noContribution.risk,0);assert.equal(noContribution.cause,null);});
test('rollMortality is deterministic, accepts an explicit rng, and does not mutate the person or touch actionCounter',()=>{const c=ctx(),p={id:'roll',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'injury',5,{world:w,known:true,state:'diagnosed'});p.medical.conditions[0].yearsActive=10;const counterBefore=p.medical.actionCounter;const first=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950});const second=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950});assert.equal(first.died,second.died);assert.equal(first.roll,second.roll);assert.equal(p.medical.actionCounter,counterBefore);assert.equal(p.alive,undefined);const forced=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950},{rng:zeroRng()});assert.equal(forced.died,true);const safe=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950},{rng:oneRng()});assert.equal(safe.died,false);});
test('history records conditionInstanceId alongside conditionId',()=>{const c=ctx(),p={id:'hist',age:30,health:70,conditions:[]},w={seed:'x',year:1950};const cond=c.MedicalSystem.addCondition(p,'injury',3,{world:w});const entry=p.medical.history.find(h=>h.kind==='onset');assert.equal(entry.conditionInstanceId,cond.instanceId);assert.equal(entry.conditionId,cond.id);});

// --- Fix 1: optional-integer normalization for lastTickYear / lastProgressionYear ---
test('numeric zero lastTickYear is preserved through migration',()=>{const c=ctx(),p={id:'ztick',age:30,health:70,conditions:[],medical:{lastTickYear:0}};c.MedicalSystem.migrate(p,{year:1950});assert.strictEqual(p.medical.lastTickYear,0);});
test('string zero lastTickYear becomes numeric zero',()=>{const c=ctx(),p={id:'ztickstr',age:30,health:70,conditions:[],medical:{lastTickYear:'0'}};c.MedicalSystem.migrate(p,{year:1950});assert.strictEqual(p.medical.lastTickYear,0);});
test('numeric-string lastTickYear becomes an integer',()=>{const c=ctx(),p={id:'strtick',age:30,health:70,conditions:[],medical:{lastTickYear:'1950'}};c.MedicalSystem.migrate(p,{year:1950});assert.strictEqual(p.medical.lastTickYear,1950);});
test('fractional lastTickYear is rounded during migration',()=>{const c=ctx(),p={id:'fractick',age:30,health:70,conditions:[],medical:{lastTickYear:1950.6}};c.MedicalSystem.migrate(p,{year:1960});assert.strictEqual(p.medical.lastTickYear,1951);});
test('fractional lastProgressionYear is rounded during migration',()=>{const c=ctx(),p={id:'fracprog',age:30,health:70,conditions:[{id:'injury',lastProgressionYear:1950.4}]};c.MedicalSystem.migrate(p,{year:1960});assert.strictEqual(p.medical.conditions[0].lastProgressionYear,1950);});
test('nonfinite optional years normalize to null',()=>{const c=ctx(),p={id:'nonfinite',age:30,health:70,conditions:[{id:'injury',lastProgressionYear:NaN}],medical:{lastTickYear:Infinity}};c.MedicalSystem.migrate(p,{year:1950});assert.strictEqual(p.medical.lastTickYear,null);assert.strictEqual(p.medical.conditions[0].lastProgressionYear,null);});
test('unparseable optional years normalize to null',()=>{const c=ctx(),p={id:'unparse',age:30,health:70,conditions:[{id:'injury',lastProgressionYear:''}],medical:{lastTickYear:'not-a-year'}};c.MedicalSystem.migrate(p,{year:1950});assert.strictEqual(p.medical.lastTickYear,null);assert.strictEqual(p.medical.conditions[0].lastProgressionYear,null);});
test('optional-year normalization is idempotent across repeated migration',()=>{const c=ctx(),p={id:'idempyear',age:30,health:70,conditions:[{id:'injury',lastProgressionYear:'1950'}],medical:{lastTickYear:'1950.6'}};c.MedicalSystem.migrate(p,{year:1960});const snapshot=JSON.stringify(p.medical);c.MedicalSystem.migrate(p,{year:1960});assert.equal(JSON.stringify(p.medical),snapshot);});
test('migrated string lastTickYear prevents a second tick for the same numeric year',()=>{const c=ctx(),p={id:'ticklock',age:30,health:70,conditions:[],medical:{lastTickYear:'1950'}},w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});const result=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(result.applied,false);assert.equal(result.reason,'already-applied');});
test('migrated string lastProgressionYear prevents a second progression for the same numeric year',()=>{const c=ctx(),p={id:'proglock',age:30,health:70,conditions:[{id:'strain',severity:3,known:true,state:'diagnosed',lastProgressionYear:'1950'}]},w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});const before=JSON.stringify(p.medical.conditions[0]);const result=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(result.progressedConditions.includes(p.medical.conditions[0].instanceId),false);assert.equal(JSON.stringify(p.medical.conditions[0]),before);});

// --- Fix 2: reconcile pre-existing active chronic duplicates ---
function chronicPerson(id,extraConditions){const conditions=[{id:'chronic',instanceId:'condition:'+id+':1940:0001',severity:2,state:'chronic',known:true,onsetYear:1945,onsetAge:35},{id:'chronic',instanceId:'condition:'+id+':1940:0002',severity:4,state:'chronic',known:true,onsetYear:1942,onsetAge:32}];if(extraConditions)conditions.push(...extraConditions);return {id,age:40,health:70,conditions};}
test('two pre-existing active chronic records reconcile into one',()=>{const c=ctx(),p=chronicPerson('dupe2'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const active=c.MedicalSystem.activeConditions(p).filter(x=>x.definitionId==='chronic');assert.equal(active.length,1);});
test('three pre-existing active chronic records reconcile into one',()=>{const c=ctx(),p=chronicPerson('dupe3');p.conditions.push({id:'chronic',instanceId:'condition:dupe3:1940:0003',severity:1,state:'chronic',known:true,onsetYear:1948,onsetAge:38});const w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const active=c.MedicalSystem.activeConditions(p).filter(x=>x.definitionId==='chronic');assert.equal(active.length,1);});
test('canonical selection is independent of array order',()=>{const c=ctx(),p1=chronicPerson('order1'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p1,{year:1950});c.MedicalSystem.tickPerson(w,p1,{world:w,year:1950});const canonical1=c.MedicalSystem.activeConditions(p1).find(x=>x.definitionId==='chronic').instanceId;const p2=chronicPerson('order1');p2.conditions.reverse();c.MedicalSystem.migrate(p2,{year:1950});c.MedicalSystem.tickPerson(w,p2,{world:w,year:1950});const canonical2=c.MedicalSystem.activeConditions(p2).find(x=>x.definitionId==='chronic').instanceId;assert.equal(canonical1,'condition:order1:1940:0001');assert.equal(canonical2,canonical1);});
test('reconciliation retains the maximum finite severity',()=>{const c=ctx(),p=chronicPerson('sev'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const canonical=c.MedicalSystem.activeConditions(p).find(x=>x.definitionId==='chronic');assert.equal(canonical.severity,4);});
test('reconciliation retains the earliest onset age and year',()=>{const c=ctx(),p=chronicPerson('onset'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const canonical=c.MedicalSystem.activeConditions(p).find(x=>x.definitionId==='chronic');assert.equal(canonical.onsetYear,1942);assert.equal(canonical.onsetAge,32);});
test('noncanonical duplicates remain in history as resolved',()=>{const c=ctx(),p=chronicPerson('resolvedhist'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const duplicate=p.medical.conditions.find(x=>x.instanceId==='condition:resolvedhist:1940:0002');assert.equal(duplicate.state,'resolved');assert.equal(duplicate.resolved,true);});
test('reconciliation appends one canonical merge record and one resolved record per source',()=>{const c=ctx(),p=chronicPerson('histcount'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const mergeEntries=p.medical.history.filter(h=>h.kind==='chronic'&&h.note&&h.note.indexOf('merged duplicate chronic instances')===0);const resolvedEntries=p.medical.history.filter(h=>h.kind==='resolved'&&h.note&&h.note.indexOf('merged into chronic instance')===0);assert.equal(mergeEntries.length,1);assert.equal(resolvedEntries.length,1);});
test('a repeated same-year tick does not add duplicate reconciliation history',()=>{const c=ctx(),p=chronicPerson('samehist'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const historyLength=p.medical.history.length;c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(p.medical.history.length,historyLength);});
test('a treated duplicate preserves its treatment course onto the canonical record',()=>{const c=ctx(),p=chronicPerson('treated1');p.conditions[1].state='treated';p.conditions[1].treatment='basic';p.conditions[1].adherence=1;p.conditions[1].lastTreatmentYear=1950;const w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const canonical=c.MedicalSystem.activeConditions(p).find(x=>x.definitionId==='chronic');assert.equal(canonical.state,'treated');assert.equal(canonical.treatment,'basic');assert.equal(canonical.lastTreatmentYear,1950);});
test('the treated duplicate with the latest treatment year wins',()=>{const c=ctx(),p=chronicPerson('treated2');p.conditions[0].state='treated';p.conditions[0].treatment='rest';p.conditions[0].adherence=1;p.conditions[0].lastTreatmentYear=1946;p.conditions[1].state='treated';p.conditions[1].treatment='specialist';p.conditions[1].adherence=1;p.conditions[1].lastTreatmentYear=1949;const w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const canonical=c.MedicalSystem.activeConditions(p).find(x=>x.definitionId==='chronic');assert.equal(canonical.treatment,'specialist');assert.equal(canonical.lastTreatmentYear,1949);});
test('duplicate chronic records no longer double-count in health burden',()=>{const c=ctx(),single={id:'burden-single',age:40,health:70,conditions:[{id:'chronic',instanceId:'condition:burden-single:1940:0001',severity:4,state:'chronic',known:true,onsetYear:1945,onsetAge:35}]},dup=chronicPerson('burden-dup');dup.conditions.forEach(x=>x.severity=4);const w={seed:'x',year:1950};c.MedicalSystem.migrate(single,{year:1950});c.MedicalSystem.migrate(dup,{year:1950});const singleResult=c.MedicalSystem.tickPerson(w,single,{world:w,year:1950});const dupResult=c.MedicalSystem.tickPerson(w,dup,{world:w,year:1950});assert.equal(dupResult.healthDelta,singleResult.healthDelta);});
test('duplicate chronic records no longer double-count in mortality contribution',()=>{const c=ctx(),single={id:'mort-single',age:40,health:70,conditions:[{id:'chronic',instanceId:'condition:mort-single:1940:0001',severity:5,state:'chronic',known:true,onsetYear:1940,onsetAge:30,yearsActive:10}]},dup=chronicPerson('mort-dup');dup.conditions.forEach(x=>{x.severity=5;x.yearsActive=10;});const w={seed:'x',year:1950};c.MedicalSystem.migrate(single,{year:1950});c.MedicalSystem.migrate(dup,{year:1950});c.MedicalSystem.tickPerson(w,single,{world:w,year:1950});c.MedicalSystem.tickPerson(w,dup,{world:w,year:1950});const singleDetails=c.MedicalSystem.mortalityDetails(w,single,{world:w,year:1950});const dupDetails=c.MedicalSystem.mortalityDetails(w,dup,{world:w,year:1950});assert.ok(Math.abs(dupDetails.risk-singleDetails.risk)<1e-9);});
test('a later respiratory/infection chronic conversion merges into the existing canonical chronic instance',()=>{const c=ctx(),p=chronicPerson('conv'),w={seed:'chronic-seed',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const canonicalId=c.MedicalSystem.activeConditions(p).find(x=>x.definitionId==='chronic').instanceId;c.MedicalSystem.addCondition(p,'respiratory',3,{world:w,known:true,state:'diagnosed'});p.medical.conditions.find(x=>x.definitionId==='respiratory').yearsActive=3;const streamFor=()=>({next:()=>0});c.MedicalSystem.tickPerson(w,p,{world:w,year:1951},{streamFor});const activeChronic=c.MedicalSystem.activeConditions(p).filter(x=>x.definitionId==='chronic');assert.equal(activeChronic.length,1);assert.equal(activeChronic[0].instanceId,canonicalId);});
test('save/reload migration and a repeated tick remain byte-for-byte deterministic',()=>{const c=ctx(),p=chronicPerson('saveload'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const saved=JSON.parse(JSON.stringify(p));c.MedicalSystem.migrate(saved,{year:1950});c.MedicalSystem.tickPerson(w,saved,{world:w,year:1950});assert.equal(JSON.stringify(saved.medical),JSON.stringify(p.medical));});

// --- Fix 3: invariant reports duplicate active chronic conditions ---
test('duplicate active chronic conditions are reported before reconciliation and cleared after',()=>{const c=ctx(),p=chronicPerson('invariant'),w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});const before=c.MedicalSystem.checkInvariants(p);assert.ok(before.includes('multiple active chronic conditions'));c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const after=c.MedicalSystem.checkInvariants(p);assert.equal(after.includes('multiple active chronic conditions'),false);});
