'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {createGameContext}=require('./helpers/vm-loader');
function ctx(){return createGameContext(['js/systems/condition-registry.js','js/systems/medical-system.js']);}
test('medical core source has no UTF-8 byte-order mark',()=>{const bytes=fs.readFileSync('js/systems/medical-system.js');assert.notEqual(bytes[0],0xEF);assert.equal(bytes.toString('utf8').charCodeAt(0),"'".charCodeAt(0));});
test('registry is immutable and complete',()=>{const c=ctx();assert.equal(c.ConditionRegistry.allConditions().length,5);assert.equal(c.ConditionRegistry.allTreatments().length,4);const x=c.ConditionRegistry.condition('injury');x.name='x';assert.equal(c.ConditionRegistry.condition('injury').name,'Lingering injury');assert.equal(c.ConditionRegistry.condition('none'),null);});
test('migration is deterministic for subject and NPC shapes',()=>{const c=ctx(),a={id:'A',age:40,health:60,conditions:[{id:'strain',severity:2,known:true,years:2}]};c.MedicalSystem.ensureMedicalState(a,{year:1960});const json=JSON.stringify(a);c.MedicalSystem.migrate(a,{year:1960});assert.equal(JSON.stringify(a),json);assert.equal(a.medical.conditions[0].state,'diagnosed');assert.equal(c.MedicalSystem.checkInvariants(a).length,0);const n={id:'npc:test',birthYear:1920,health:{general:72,conditions:[]}};c.MedicalSystem.ensureMedicalState(n,{year:1960});assert.equal(n.health.general,72);assert.strictEqual(n.health.conditions,n.health.medical.conditions);});
test('active episode merges and resolved episode receives a new identity',()=>{const c=ctx(),p={id:'person',age:30,health:80,healthCap:100,conditions:[]},w={seed:'x',year:1950};const first=c.MedicalSystem.addCondition(p,'injury',3,{world:w});assert.strictEqual(c.MedicalSystem.addCondition(p,'injury',5,{world:w}),first);assert.equal(first.severity,5);first.state='resolved';const second=c.MedicalSystem.addCondition(p,'injury',2,{world:w});assert.notEqual(second.instanceId,first.instanceId);assert.equal(p.medical.conditions.length,2);});
test('core has no global random or active-game references',()=>{const src=fs.readFileSync('js/systems/medical-system.js','utf8');assert.doesNotMatch(src,/Math\.random\(|Random\.next\(|(?<![.\w])chance\(|(?<![.\w])pick\(|(?<![.\w])RI\(|(?<![.\w])R\(/);assert.doesNotMatch(src,/(?<![.\w])S(?![\w])|(?<![.\w])World(?![\w])/);});
test('new subject state has schema two aliases and counters',()=>{const c=ctx(),p={id:'subject:one',age:20,health:70,conditions:[]};const m=c.MedicalSystem.ensureMedicalState(p,{year:1940});assert.equal(m.schemaVersion,2);assert.strictEqual(p.conditions,m.conditions);assert.equal(m.instanceCounter,0);assert.equal(m.actionCounter,0);assert.equal(c.MedicalSystem.activeConditions(p).length,0);});
test('legacy schema preserves history and creates stable instance ids',()=>{const c=ctx(),p={id:'legacy',age:40,health:60,conditions:[{id:'strain',severity:2,known:true,years:2}],medical:{schemaVersion:1,history:[{kind:'note'}],conditions:[{id:'strain',severity:2,known:true,years:2}]}};c.MedicalSystem.migrate(p,{year:1960});const x=p.medical.conditions[0];assert.equal(x.definitionId,'strain');assert.equal(x.id,'strain');assert.equal(x.state,'diagnosed');assert.equal(x.yearsActive,2);assert.match(x.instanceId,/^condition:legacy:1960:0001$/);assert.equal(p.medical.history.length,1);});
test('unknown legacy definitions remain opaque and are reported by invariants',()=>{const c=ctx(),p={id:'unknown',age:40,health:60,conditions:[{id:'retired-diagnosis',severity:4,state:'remission',years:3,source:'old save'}]};c.MedicalSystem.migrate(p,{year:1960});const x=p.medical.conditions[0];assert.equal(x.definitionId,'retired-diagnosis');assert.equal(x.id,'retired-diagnosis');assert.equal(x.severity,4);assert.equal(x.state,'remission');assert.equal(x.yearsActive,3);assert.equal(x.source,'old save');assert.equal(x.exposureType,'unknown');assert.equal(x.contagious,false);assert.match(JSON.stringify(p),/retired-diagnosis/);assert.deepEqual(Array.from(c.MedicalSystem.checkInvariants(p)),['unknown condition definition: retired-diagnosis']);});
test('duplicate malformed and foreign instance IDs are reconciled in array order',()=>{const c=ctx(),p={id:'Person X',age:30,health:70,conditions:[{id:'injury',instanceId:'condition:person-x:1950:0001'},{id:'strain',instanceId:'condition:person-x:1950:0001'},{id:'infection',instanceId:'bad'},{id:'respiratory',instanceId:'condition:other:1950:0007'}]};c.MedicalSystem.migrate(p,{year:1950});const ids=p.medical.conditions.map(x=>x.instanceId);assert.equal(ids[0],'condition:person-x:1950:0001');assert.equal(new Set(ids).size,4);assert.ok(ids.slice(1).every(id=>/^condition:person-x:1950:\d{4,}$/.test(id)));});
test('encoded and persisted counters determine the next episode identity',()=>{const c=ctx(),p={id:'counter',age:30,health:70,conditions:[{id:'injury',instanceId:'condition:counter:1950:0001'},{id:'strain',instanceId:'condition:counter:1950:0005'}],medical:{instanceCounter:9}};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.instanceCounter,9);p.medical.conditions[0].state='resolved';const next=c.MedicalSystem.addCondition(p,'injury',2,{world:{year:1950}});assert.match(next.instanceId,/:0010$/);});
test('onset year normalizes before id reconciliation and migration is idempotent',()=>{const c=ctx(),p={id:'year',age:20,health:70,conditions:[{id:'injury',onsetYear:1950.6},{id:'strain',onsetYear:NaN}]};c.MedicalSystem.migrate(p,{year:1960});assert.equal(p.medical.conditions[0].onsetYear,1951);assert.equal(p.medical.conditions[1].onsetYear,1960);const snapshot=JSON.stringify(p.medical);c.MedicalSystem.migrate(p,{year:1960});assert.equal(JSON.stringify(p.medical),snapshot);});
test('zero severity is valid while absent and invalid severities use definition defaults',()=>{const c=ctx(),p={id:'zero',age:30,health:70,conditions:[]},w={year:1950};const zero=c.MedicalSystem.addCondition(p,'injury',0,{world:w});assert.equal(zero.severity,0);assert.equal(c.MedicalSystem.addCondition(p,'injury',0,{world:w}).severity,0);zero.state='resolved';assert.equal(c.MedicalSystem.addCondition(p,'strain',undefined,{world:w}).severity,2);p.medical.conditions.find(x=>x.id==='strain').state='resolved';assert.equal(c.MedicalSystem.addCondition(p,'infection',NaN,{world:w}).severity,3);});
test('save reload migration preserves condition identity and counters',()=>{const c=ctx(),p={id:'save',age:30,health:70,conditions:[]};c.MedicalSystem.addCondition(p,'injury',3,{world:{year:1950}});const saved=JSON.parse(JSON.stringify(p));c.MedicalSystem.migrate(saved,{year:1950});assert.deepEqual(JSON.parse(JSON.stringify(saved.medical)),JSON.parse(JSON.stringify(p.medical)));});
test('normalization uses explicit person age rather than global subject',()=>{const c=ctx(),a={id:'a',age:13,health:70,conditions:[]},b={id:'b',age:61,health:70,conditions:[]};c.S={age:99,health:1};const x=c.MedicalSystem.addCondition(a,'strain',2,{world:{year:1930}}),y=c.MedicalSystem.addCondition(b,'chronic',3,{world:{year:1980}});assert.equal(x.onsetAge,13);assert.equal(y.onsetAge,61);});
test('invalid partial medical data is repaired safely',()=>{const c=ctx(),p={id:'repair',age:30,health:NaN,conditions:[{id:'injury',severity:NaN}],medical:{conditions:null,history:null,instanceCounter:-3,actionCounter:'bad'}};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.instanceCounter,1);assert.equal(p.medical.actionCounter,0);assert.ok(Array.isArray(p.medical.history));assert.ok(Array.isArray(p.medical.conditions));assert.equal(c.MedicalSystem.checkInvariants(p).length,0);});
test('history is bounded to the latest twenty four records',()=>{const c=ctx(),p={id:'history',age:20,health:70,conditions:[]};for(let i=0;i<30;i++)c.MedicalSystem.history(p,'note',null,String(i),{world:{year:1900+i}});assert.equal(p.medical.history.length,24);assert.equal(p.medical.history[0].note,'6');});
test('isolated streams are deterministic and do not advance personal random',()=>{const c=ctx(),w={seed:'medical-test',year:1950},p={id:'rng',age:30,health:70,conditions:[]};c.Random.setSeed('personal');const first=c.Random.next(),control=c.Random.next();c.Random.setSeed('personal');assert.equal(c.Random.next(),first);const a=c.MedicalSystem.stream(w,p,1950,'migration','a').next(),b=c.MedicalSystem.stream(w,p,1950,'migration','a').next();assert.equal(a,b);assert.equal(c.Random.next(),control);});
test('public API includes reusable care methods and annual progression methods',()=>{const c=ctx(),keys=Object.keys(c.MedicalSystem);['contextFor','accessFor','exposureRisk','expose','examine','treatmentOptions','treatmentCost','treat','hoursPenalty','educationPenalty','workPenalty','summary','tickPerson','mortalityDetails','rollMortality'].forEach(key=>assert.equal(typeof c.MedicalSystem[key],'function'));['startOutbreak','tickOutbreak'].forEach(key=>assert.equal(keys.includes(key),false));});
test('known lifecycle states imply known while symptomatic known remains valid',()=>{const c=ctx();['diagnosed','treated','remission','chronic'].forEach(state=>{const p={id:state,age:30,health:70,conditions:[{id:'injury',state,known:false}]};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.conditions[0].known,true);});const p={id:'symptomatic',age:30,health:70,conditions:[{id:'injury',state:'symptomatic',known:true}]};c.MedicalSystem.migrate(p,{year:1950});assert.equal(c.MedicalSystem.checkInvariants(p).length,0);});
test('raw subject and npc health is repaired during migration',()=>{const c=ctx(),s={id:'s',age:20,health:NaN,healthCap:80,conditions:[]},n={id:'n',birthYear:1900,health:{general:NaN,conditions:[]}};c.MedicalSystem.migrate(s,{year:1950});c.MedicalSystem.migrate(n,{year:1950});assert.equal(s.health,50);assert.equal(n.health.general,70);s.health=120;c.MedicalSystem.migrate(s,{year:1950});assert.equal(s.health,80);s.health=-2;c.MedicalSystem.migrate(s,{year:1950});assert.equal(s.health,0);});
test('zero instance counter is repaired and migration stays stable',()=>{const c=ctx(),p={id:'zero-id',age:20,health:70,conditions:[{id:'injury',instanceId:'condition:zero-id:1950:0000'}]};c.MedicalSystem.migrate(p,{year:1950});assert.equal(/:0000$/.test(p.medical.conditions[0].instanceId),false);const snapshot=JSON.stringify(p.medical);c.MedicalSystem.migrate(p,{year:1950});assert.equal(JSON.stringify(p.medical),snapshot);});

// --- Phase 4A-3: annual progression and mortality ---
function zeroRng(){return {next:()=>0};}
function oneRng(){return {next:()=>0.999999};}
test('tickPerson is idempotent for the same person-year and does not rewind on a stale year',()=>{const c=ctx(),p={id:'idem',age:30,health:70,conditions:[]},w={seed:'x',year:1950};const first=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(first.applied,true);const second=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(second.applied,false);assert.equal(second.reason,'already-applied');const before=JSON.stringify(p.medical);const stale=c.MedicalSystem.tickPerson(w,p,{world:w,year:1949});assert.equal(stale.applied,false);assert.equal(stale.reason,'stale-year');assert.equal(JSON.stringify(p.medical),before);const next=c.MedicalSystem.tickPerson(w,p,{world:w,year:1951});assert.equal(next.applied,true);assert.equal(p.medical.lastTickYear,1951);});
test('tickPerson does not consume actionCounter or the global personal random stream',()=>{const c=ctx(),p={id:'rng-safe',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.Random.setSeed('personal');const before=c.Random.next();c.Random.setSeed('personal');c.MedicalSystem.addCondition(p,'injury',4,{world:w});const counterBefore=p.medical.actionCounter;c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(p.medical.actionCounter,counterBefore);assert.equal(c.Random.next(),before);});
test('latent condition decrements incubation and becomes symptomatic exactly once with one history entry',()=>{const c=ctx(),p={id:'latent',age:20,health:70,conditions:[{id:'infection',state:'latent',known:false,incubationLeft:1}]},w={seed:'x',year:1950};c.MedicalSystem.migrate(p,{year:1950});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});const cond=p.medical.conditions[0];assert.equal(cond.state,'symptomatic');assert.equal(p.medical.history.filter(h=>h.kind==='symptom').length,1);c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(p.medical.history.filter(h=>h.kind==='symptom').length,1);});
test('treatment filed in the current year is protected from untreated burden and receives no course relief until next year',()=>{const c=ctx(),p={id:'grace',age:30,health:70,healthCap:100,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'injury',4,{world:w,known:true,state:'diagnosed'});const cond=p.medical.conditions[0];cond.known=true;cond.state='treated';cond.treated=true;cond.treatment='basic';cond.lastTreatmentYear=1950;const result=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(result.healthDelta,0);assert.equal(cond.state,'treated');assert.equal(cond.severity,4);const nextYear=c.MedicalSystem.tickPerson(w,p,{world:w,year:1951});assert.notEqual(nextYear.healthDelta,undefined);assert.notEqual(cond.state,'treated');});
test('untreated burden formula applies health, strain happiness, and hour penalties correctly',()=>{const c=ctx(),p={id:'burden',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'strain',5,{world:w,known:true,state:'diagnosed'});const result=c.MedicalSystem.tickPerson(w,p,{world:w,year:1950});assert.equal(result.healthDelta,-3);assert.equal(result.happinessDelta,-3);assert.equal(result.yearHoursPenalty,2);});
test('chronic conversion preserves instanceId when no existing chronic record and merges into one chronic record otherwise',()=>{const c=ctx(),p={id:'chronic',age:30,health:70,conditions:[]},w={seed:'chronic-seed',year:1950};c.MedicalSystem.addCondition(p,'respiratory',3,{world:w,known:true,state:'diagnosed'});p.medical.conditions[0].yearsActive=3;const originalId=p.medical.conditions[0].instanceId;const streamFor=()=>({next:()=>0});c.MedicalSystem.tickPerson(w,p,{world:w,year:1950},{streamFor});const chronicCondition=p.medical.conditions.find(x=>x.definitionId==='chronic');assert.ok(chronicCondition);assert.equal(chronicCondition.instanceId,originalId);c.MedicalSystem.addCondition(p,'infection',3,{world:w,known:true,state:'diagnosed'});p.medical.conditions.find(x=>x.definitionId==='infection').yearsActive=3;c.MedicalSystem.tickPerson(w,p,{world:w,year:1951},{streamFor});const activeChronic=c.MedicalSystem.activeConditions(p).filter(x=>x.definitionId==='chronic');assert.equal(activeChronic.length,1);});
test('mortalityDetails contributes only for severe untreated conditions and clamps risk to 0.16, no randomness or mutation',()=>{const c=ctx(),p={id:'mortal',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'injury',5,{world:w,known:true,state:'diagnosed'});c.MedicalSystem.addCondition(p,'chronic',5,{world:w,known:true,state:'diagnosed'});p.medical.conditions[0].yearsActive=10;p.medical.conditions[1].yearsActive=10;c.MedicalSystem.syncLegacy(p);const before=JSON.stringify(p.medical);const details=c.MedicalSystem.mortalityDetails(w,p,{world:w,year:1950});assert.ok(details.risk>0);assert.ok(details.risk<=0.16);assert.equal(JSON.stringify(p.medical),before);const treated={id:'t',age:30,health:70,conditions:[]};c.MedicalSystem.addCondition(treated,'injury',5,{world:w,known:true,state:'treated'});const noContribution=c.MedicalSystem.mortalityDetails(w,treated,{world:w,year:1950});assert.equal(noContribution.risk,0);assert.equal(noContribution.cause,null);});
test('rollMortality is deterministic, accepts an explicit rng, and does not mutate the person or touch actionCounter',()=>{const c=ctx(),p={id:'roll',age:30,health:70,conditions:[]},w={seed:'x',year:1950};c.MedicalSystem.addCondition(p,'injury',5,{world:w,known:true,state:'diagnosed'});p.medical.conditions[0].yearsActive=10;const counterBefore=p.medical.actionCounter;const first=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950});const second=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950});assert.equal(first.died,second.died);assert.equal(first.roll,second.roll);assert.equal(p.medical.actionCounter,counterBefore);assert.equal(p.alive,undefined);const forced=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950},{rng:zeroRng()});assert.equal(forced.died,true);const safe=c.MedicalSystem.rollMortality(w,p,{world:w,year:1950},{rng:oneRng()});assert.equal(safe.died,false);});
test('history records conditionInstanceId alongside conditionId',()=>{const c=ctx(),p={id:'hist',age:30,health:70,conditions:[]},w={seed:'x',year:1950};const cond=c.MedicalSystem.addCondition(p,'injury',3,{world:w});const entry=p.medical.history.find(h=>h.kind==='onset');assert.equal(entry.conditionInstanceId,cond.instanceId);assert.equal(entry.conditionId,cond.id);});
