'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {createGameContext}=require('./helpers/vm-loader');
function ctx(){return createGameContext(['js/systems/condition-registry.js','js/systems/medical-system.js']);}
test('registry is immutable and complete',()=>{const c=ctx();assert.equal(c.ConditionRegistry.allConditions().length,5);assert.equal(c.ConditionRegistry.allTreatments().length,4);const x=c.ConditionRegistry.condition('injury');x.name='x';assert.equal(c.ConditionRegistry.condition('injury').name,'Lingering injury');assert.equal(c.ConditionRegistry.condition('none'),null);});
test('migration is deterministic for subject and NPC shapes',()=>{const c=ctx(),a={id:'A',age:40,health:60,conditions:[{id:'strain',severity:2,known:true,years:2}]};c.MedicalSystem.ensureMedicalState(a,{year:1960});const json=JSON.stringify(a);c.MedicalSystem.migrate(a,{year:1960});assert.equal(JSON.stringify(a),json);assert.equal(a.medical.conditions[0].state,'diagnosed');assert.equal(c.MedicalSystem.checkInvariants(a).length,0);const n={id:'npc:test',birthYear:1920,health:{general:72,conditions:[]}};c.MedicalSystem.ensureMedicalState(n,{year:1960});assert.equal(n.health.general,72);assert.strictEqual(n.health.conditions,n.health.medical.conditions);});
test('active episode merges and resolved episode receives a new identity',()=>{const c=ctx(),p={id:'person',age:30,health:80,healthCap:100,conditions:[]},w={seed:'x',year:1950};const first=c.MedicalSystem.addCondition(p,'injury',3,{world:w});assert.strictEqual(c.MedicalSystem.addCondition(p,'injury',5,{world:w}),first);assert.equal(first.severity,5);first.state='resolved';const second=c.MedicalSystem.addCondition(p,'injury',2,{world:w});assert.notEqual(second.instanceId,first.instanceId);assert.equal(p.medical.conditions.length,2);});
test('core has no global random or active-game references',()=>{const src=fs.readFileSync('js/systems/medical-system.js','utf8');assert.doesNotMatch(src,/Math\.random\(|Random\.next\(|(?<![.\w])chance\(|(?<![.\w])pick\(|(?<![.\w])RI\(|(?<![.\w])R\(/);assert.doesNotMatch(src,/(?<![.\w])S(?![\w])|(?<![.\w])World(?![\w])/);});
test('new subject state has schema two aliases and counters',()=>{const c=ctx(),p={id:'subject:one',age:20,health:70,conditions:[]};const m=c.MedicalSystem.ensureMedicalState(p,{year:1940});assert.equal(m.schemaVersion,2);assert.strictEqual(p.conditions,m.conditions);assert.equal(m.instanceCounter,0);assert.equal(m.actionCounter,0);assert.equal(c.MedicalSystem.activeConditions(p).length,0);});
test('legacy schema preserves history and creates stable instance ids',()=>{const c=ctx(),p={id:'legacy',age:40,health:60,conditions:[{id:'strain',severity:2,known:true,years:2}],medical:{schemaVersion:1,history:[{kind:'note'}],conditions:[{id:'strain',severity:2,known:true,years:2}]}};c.MedicalSystem.migrate(p,{year:1960});const x=p.medical.conditions[0];assert.equal(x.definitionId,'strain');assert.equal(x.id,'strain');assert.equal(x.state,'diagnosed');assert.equal(x.yearsActive,2);assert.match(x.instanceId,/^condition:legacy:1960:0001$/);assert.equal(p.medical.history.length,1);});
test('unknown legacy definitions remain opaque and are not converted to chronic',()=>{const c=ctx(),p={id:'unknown',age:40,health:60,conditions:[{id:'retired-diagnosis',severity:4,state:'remission',years:3,source:'old save'}]};c.MedicalSystem.migrate(p,{year:1960});const x=p.medical.conditions[0];assert.equal(x.definitionId,'retired-diagnosis');assert.equal(x.id,'retired-diagnosis');assert.equal(x.severity,4);assert.equal(x.state,'remission');assert.equal(x.yearsActive,3);assert.equal(x.source,'old save');assert.equal(x.exposureType,'unknown');assert.equal(x.contagious,false);assert.equal(c.MedicalSystem.checkInvariants(p).length,0);});
test('save reload migration preserves condition identity and counters',()=>{const c=ctx(),p={id:'save',age:30,health:70,conditions:[]};c.MedicalSystem.addCondition(p,'injury',3,{world:{year:1950}});const saved=JSON.parse(JSON.stringify(p));c.MedicalSystem.migrate(saved,{year:1950});assert.deepEqual(JSON.parse(JSON.stringify(saved.medical)),JSON.parse(JSON.stringify(p.medical)));});
test('normalization uses explicit person age rather than global subject',()=>{const c=ctx(),a={id:'a',age:13,health:70,conditions:[]},b={id:'b',age:61,health:70,conditions:[]};c.S={age:99,health:1};const x=c.MedicalSystem.addCondition(a,'strain',2,{world:{year:1930}}),y=c.MedicalSystem.addCondition(b,'chronic',3,{world:{year:1980}});assert.equal(x.onsetAge,13);assert.equal(y.onsetAge,61);});
test('invalid partial medical data is repaired safely',()=>{const c=ctx(),p={id:'repair',age:30,health:NaN,conditions:[{id:'injury',severity:NaN}],medical:{conditions:null,history:null,instanceCounter:-3,actionCounter:'bad'}};c.MedicalSystem.migrate(p,{year:1950});assert.equal(p.medical.instanceCounter,1);assert.equal(p.medical.actionCounter,0);assert.ok(Array.isArray(p.medical.history));assert.ok(Array.isArray(p.medical.conditions));assert.equal(c.MedicalSystem.checkInvariants(p).length,0);});
test('history is bounded to the latest twenty four records',()=>{const c=ctx(),p={id:'history',age:20,health:70,conditions:[]};for(let i=0;i<30;i++)c.MedicalSystem.history(p,'note',null,String(i),{world:{year:1900+i}});assert.equal(p.medical.history.length,24);assert.equal(p.medical.history[0].note,'6');});
test('isolated streams are deterministic and do not advance personal random',()=>{const c=ctx(),w={seed:'medical-test',year:1950},p={id:'rng',age:30,health:70,conditions:[]};c.Random.setSeed('personal');const first=c.Random.next(),control=c.Random.next();c.Random.setSeed('personal');assert.equal(c.Random.next(),first);const a=c.MedicalSystem.stream(w,p,1950,'migration','a').next(),b=c.MedicalSystem.stream(w,p,1950,'migration','a').next();assert.equal(a,b);assert.equal(c.Random.next(),control);});
test('public API contains only Phase 4A-1 foundation methods',()=>{const c=ctx(),keys=Object.keys(c.MedicalSystem).sort();assert.deepEqual(JSON.parse(JSON.stringify(keys)),['SCHEMA_VERSION','activeConditions','addCondition','ageOf','applyHealthDelta','checkInvariants','conditionByRef','ensureMedicalState','getHealth','getHealthCap','history','isSubjectLike','migrate','normalizeCondition','personKey','setHealth','stream','syncLegacy','yearOf'].sort());});
